### ISSUE TITLE
Implement Future/allow extracting channel on JoinHandle

### ISSUE THREAD

**Issue by Ten0** [robinfriedli/rusty_pool#6]
My use-case is to use this as an executor for a webserver.
The webserver is asynchronous, but the code executed to compute the response is not.
I need to spawn getting the result as a future on the webserver's asynchronous executor.

I can't do this using `JoinHandle`, because it does not implement `Future`, so I basically have to reimplement `evaluate`, returning the `Receiver` directly from my code.

It would be great if I could extract the `Receiver` from the `JoinHandle`, (or await the `JoinHandle` directly - probably cleaner but longer to implement).

**Comment by robinfriedli** [comment]
The receiver is now public as of 0.7.0
